### ISSUE TITLE
Docker Compose (inside)

### ISSUE THREAD

**Issue by ItsNoted** [biolds/sosse#8]
This is a basic Docker Compose for those who need one.

```
services:
    sosse:
        volumes:
            - /docker/sosse/data:/etc/sosse/
            - /docker/sosse/logs:/var/log/sosse/
            - /docker/sosse/archives:/var/lib/sosse/html
        ports:
            - 8005:80
        image: biolds/sosse:latest
```
